source("./src/00_configurations.R")
source("./src/Soria/01_prepare_files_and_folders.R")
source("./src/Soria/02_global_occurrence_download.R")
source("./src/Soria/03_fit_climate_model.R")
source("./src/Soria/04_fit_habitat_model.R")
