source("./src/00_configurations.R")
source("./src/Soria/01_prepare_files_and_folders.R")
source("./src/Soria/02_global_occurrence_download.R")
source("./src/Soria/03_fit_global_model.R")
source("./src/Soria/04_fit_European_model.R")
